// <auto-generated />
using System;
using System.Collections.Generic;
using BubbleTea.Services.Cart.API.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BubbleTea.Services.Cart.API.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20241015120122_AddCartItemOptions")]
    partial class AddCartItemOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cart")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("cart_id")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "BubbleTea.Services.Cart.API.Entities.Carts.CartItem.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cart_items");

                    b.HasIndex("cart_id")
                        .HasDatabaseName("ix_cart_items_cart_id");

                    b.ToTable("cart_items", "cart", t =>
                        {
                            t.HasCheckConstraint("CK_Quantity_GreaterThanZero", "quantity > 0");
                        });
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<Guid>("parameter_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parameter_id");

                    b.ComplexProperty<Dictionary<string, object>>("ExtraPrice", "BubbleTea.Services.Cart.API.Entities.Carts.Option.ExtraPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("extra_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cart_item_options");

                    b.HasIndex("parameter_id")
                        .IsUnique()
                        .HasDatabaseName("ix_cart_item_options_parameter_id");

                    b.ToTable("cart_item_options", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("cart_item_id")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_item_id");

                    b.HasKey("Id")
                        .HasName("pk_cart_item_parameters");

                    b.HasIndex("cart_item_id")
                        .HasDatabaseName("ix_cart_item_parameters_cart_item_id");

                    b.ToTable("cart_item_parameters", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_shopping_carts");

                    b.ToTable("shopping_carts", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "cart");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.CartItem", b =>
                {
                    b.HasOne("BubbleTea.Services.Cart.API.Entities.Carts.ShoppingCart", null)
                        .WithMany("Items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cart_items_shopping_carts_cart_id");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.Option", b =>
                {
                    b.HasOne("BubbleTea.Services.Cart.API.Entities.Carts.Parameter", null)
                        .WithOne("SelectedOption")
                        .HasForeignKey("BubbleTea.Services.Cart.API.Entities.Carts.Option", "parameter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_options_cart_item_parameters_parameter_id");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.Parameter", b =>
                {
                    b.HasOne("BubbleTea.Services.Cart.API.Entities.Carts.CartItem", null)
                        .WithMany("Parameters")
                        .HasForeignKey("cart_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_parameters_cart_items_cart_item_id");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.CartItem", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.Parameter", b =>
                {
                    b.Navigation("SelectedOption")
                        .IsRequired();
                });

            modelBuilder.Entity("BubbleTea.Services.Cart.API.Entities.Carts.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
